[package]
name = "ngmp_protocol_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1.40", features = ["sync","net","io-util"] }
